### PR TITLE
Add offset property

### LINKED ISSUE #1: Missing offset property
For designs which have a sidebar, it is common practice to apply the grid to the main content only.

image

An offset property would allow users to specify where the grid really starts

### PR DESCRIPTION
**Pull request by tv104**
This pull adds the ability to specify an `offset` property in the preset. (fixes #1)

It is implemented in a backwards compatible manner, so users upgrading their extension should not be affected by this

### CODE REVIEW

**Comment by tv104** [comment]
cc @imagentleman - any chance of this getting reviewed, merged and published?

**Comment by imagentleman** [comment]
@timv88 Looks great. I'm thinking we could make it more generic and support all "offsets", so, not only the left and make it more generic. Maybe offset could be an object like {top: 0, right: 0, top: 0, bottom: 0} or we could have 4 properties (offsetLeft: 0, offsetRight: 0... and so on).

**Comment by tv104** [comment]
@imagentleman I agree, those would be nice to have, especially `offsetRight` for when you're developing in an iframe with a scrollbar (like in Storybook).

I opted for the simple `offsetLeft: 0, offsetRight: 0` approach as I imagine most users won't need to specify all offsets. Most likely they will not use any, or just 1 (`offsetLeft`). So for most common use case of the new properties, the object syntax is a bit cumbersome.

To keep things simple and reduce the entry barrier, I also omitted all `offset` properties in the `defaultPreset` and only specify `offsetLeft` in the `templatePreset` . I think a brief description of the available properties on the Chrome extension page would be useful for those looking for more advanced capability.

**Comment by imagentleman** [comment]
Looks good. Merging. I'll do some tests and bump the version in a few (i'm also still thinking about how to communicate the new values...). I'll leave a comment once everything is published.

Thank you!

**Pull request merged**
